### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ricardokleinklein** [ricardokleinklein/complex_networks#1]
This is a work in progress, so the file hierarchy, names... Are not fixed.

### Section 1:
- [x] Order 
- [x] Size
- [x] Min, Max and Mean degree
- [x] Average Clustering Coefficient
- [x] Assortativity
- [x] Average Path Length
- [x] Diameter
- [x] Probability Distribution Function
- [x] Complementary Cumulative Distribution Function

### Section 2:
- [x] Erdos-Renyi model w/ parameters N, K
- [x] Erdos-Renyi model w/ parameters N, p
- [x] Watts-Strogatz model
- [x] Barabasi & Albert model
- [x] Configuration Model w/ Poisson
- [x] Configuration Model w/ Power Law
- [x] Visual comparison theory-experiment for pdf
